[mcp_servers.21st-dev]
command = "npx"
args = [
    "-y",
    "@21st-dev/magic@latest",
]

[mcp_servers.context7]
url = "https://mcp.context7.com/sse"

[mcp_servers.nano-banana-pro]
command = "npx"
args = [
    "-y",
    "@rafarafarafa/nano-banana-pro-mcp",
]
env_vars = ["GEMINI_API_KEY"]

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp"
