/**
 * Mock data for public pages when Supabase is unavailable or returns empty.
 * Used as fallback during tests or development.
 */

import type { BlogPost, Course, Instructor, TrainingClass, TrainingPath } from "@/types";

export const mockTrainingPaths: TrainingPath[] = [
  {
    id: "path-licitacoes",
    code: "LIC",
    name: "Licitações e Contratos",
    shortName: "Licitações",
    slug: "licitacoes-e-contratos",
    description: "Formação aplicada para contratação pública, gestão e fiscalização contratual.",
    icon: "Scale",
    courseCount: 3,
  },
  {
    id: "path-lgpd",
    code: "LGPD",
    name: "LGPD e Privacidade",
    shortName: "LGPD",
    slug: "lgpd-e-privacidade",
    description: "Adequação prática à LGPD e à governança de dados no setor público e privado.",
    icon: "Shield",
    courseCount: 2,
  },
  {
    id: "path-gestao-publica",
    code: "GP",
    name: "Gestão Pública",
    shortName: "Gestão Pública",
    slug: "gestao-publica",
    description: "Capacitação para orçamento, governança, riscos e execução pública.",
    icon: "Landmark",
    courseCount: 2,
  },
  {
    id: "path-compliance",
    code: "COMP",
    name: "Compliance",
    shortName: "Compliance",
    slug: "compliance",
    description: "Programas de integridade, prevenção à fraude e cultura de conformidade.",
    icon: "BadgeCheck",
    courseCount: 2,
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-nova-lei-licitacoes",
    slug: "nova-lei-de-licitacoes-na-pratica-lei-14133-21",
    title: "Nova Lei de Licitações na prática (Lei 14.133/21)",
    pathId: "path-licitacoes",
    pathName: "Licitações e Contratos",
    category: "Licitações e Contratos",
    categories: ["Licitações e Contratos"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "16h",
    durationHours: 16,
    level: "Intermediário",
    price: 1290,
    shortDescription: "Aplicação prática da Lei 14.133/21 com foco em erros recorrentes e decisões operacionais.",
    fullDescription: "Curso orientado à execução para equipes que precisam conduzir licitações sob a Lei 14.133/21 com segurança.",
    targetAudience: ["Pregoeiros", "Equipes de compras", "Gestores públicos"],
    objectives: ["Reduzir falhas em pregões", "Padronizar decisões e fluxos"],
    benefits: ["Checklists operacionais", "Casos reais de contratação"],
    modules: [
      {
        title: "Aplicação da Lei 14.133/21",
        description: "Fase preparatória, critérios e julgamento.",
        topics: ["Planejamento", "Julgamento", "Riscos e controles"],
        duration: "8h",
      },
    ],
    instructorId: "instructor-helena",
    image: "/images/courses/departamento-pessoal-esocial.jpg",
    rating: 4.8,
    studentsCount: 127,
    status: "Ativo",
    featured: true,
    featuredCourseIds: [],
    nextClassId: "class-licitacoes-ago",
  },
  {
    id: "course-lgpd-setor-publico",
    slug: "lgpd-para-o-setor-publico-da-teoria-a-rotina",
    title: "LGPD para o setor público: da teoria à rotina",
    pathId: "path-lgpd",
    pathName: "LGPD e Privacidade",
    category: "LGPD e Privacidade",
    categories: ["LGPD e Privacidade"],
    modality: "Presencial",
    modalities: ["Presencial", "Ao vivo online"],
    durationLabel: "20h",
    durationHours: 20,
    level: "Intermediário",
    price: 1690,
    shortDescription: "Adequação prática à LGPD com foco na rotina de órgãos públicos.",
    fullDescription: "Curso para transformar LGPD em rotina operacional, com base em processos reais do setor público.",
    targetAudience: ["DPOs", "Jurídico", "Gestão pública"],
    objectives: ["Adequar fluxos de dados", "Definir controles aplicáveis"],
    benefits: ["Modelos e fluxos", "Casos práticos"],
    modules: [
      {
        title: "LGPD na operação pública",
        description: "Bases legais, compartilhamento e governança.",
        topics: ["Bases legais", "Compartilhamento", "Boas práticas"],
        duration: "8h",
      },
    ],
    instructorId: "instructor-marcos",
    image: "/images/courses/comunicacao-atendimento.jpg",
    rating: 4.6,
    studentsCount: 89,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-lgpd-ago",
  },
  {
    id: "course-gestao-contratos",
    slug: "gestao-e-fiscalizacao-de-contratos-administrativos",
    title: "Gestão e fiscalização de contratos administrativos",
    pathId: "path-licitacoes",
    pathName: "Licitações e Contratos",
    category: "Licitações e Contratos",
    categories: ["Licitações e Contratos"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "12h",
    durationHours: 12,
    level: "Intermediário",
    price: 990,
    shortDescription: "Fiscalização, indicadores e gestão operacional de contratos administrativos.",
    fullDescription: "Curso focado na governança diária e na fiscalização de contratos administrativos.",
    targetAudience: ["Gestores de contratos", "Fiscalização", "Controle interno"],
    objectives: ["Fortalecer fiscalização", "Organizar execução contratual"],
    benefits: ["Roteiros de fiscalização", "Checklists práticos"],
    modules: [],
    instructorId: "instructor-helena",
    image: "/images/courses/pessoas-lideranca.jpg",
    rating: 4.7,
    studentsCount: 112,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-contratos-set",
  },
  {
    id: "course-programa-integridade",
    slug: "programa-de-integridade-e-compliance-publico",
    title: "Programa de integridade e compliance público",
    pathId: "path-compliance",
    pathName: "Compliance",
    category: "Compliance",
    categories: ["Compliance"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "16h",
    durationHours: 16,
    level: "Intermediário",
    price: 1190,
    shortDescription: "Estruturação de programas de integridade para o setor público.",
    fullDescription: "Curso para criação, governança e sustentação de programas de integridade e compliance público.",
    targetAudience: ["Compliance", "Controle interno", "Alta gestão"],
    objectives: ["Estruturar programa", "Definir indicadores e governança"],
    benefits: ["Modelos de política", "Roteiros de implantação"],
    modules: [],
    instructorId: "instructor-fernanda",
    image: "/images/courses/comunicacao-atendimento.jpg",
    rating: 4.7,
    studentsCount: 97,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-compliance-set",
  },
  {
    id: "course-planejamento-orcamentario",
    slug: "planejamento-e-execucao-orcamentaria-na-pratica",
    title: "Planejamento e execução orçamentária na prática",
    pathId: "path-gestao-publica",
    pathName: "Gestão Pública",
    category: "Gestão Pública",
    categories: ["Gestão Pública", "Administração"],
    modality: "Presencial",
    modalities: ["Presencial"],
    durationLabel: "24h",
    durationHours: 24,
    level: "Avançado",
    price: 1890,
    shortDescription: "Capacitação prática para planejamento e execução orçamentária com foco em decisão.",
    fullDescription: "Curso avançado para equipes que precisam dominar planejamento e execução orçamentária na prática.",
    targetAudience: ["Gestores públicos", "Coordenadores"],
    objectives: ["Modernizar processos", "Aumentar eficiência"],
    benefits: ["Networking", "Casos reais"],
    modules: [],
    instructorId: "instructor-roberto",
    image: "/images/courses/pessoas-lideranca.jpg",
    rating: 4.9,
    studentsCount: 156,
    status: "Ativo",
    featured: true,
    featuredCourseIds: [],
    nextClassId: "class-orcamento-out",
  },
  {
    id: "course-dpo",
    slug: "encarregado-de-dados-dpo-funcao-e-responsabilidades",
    title: "Encarregado de dados (DPO): função e responsabilidades",
    pathId: "path-lgpd",
    pathName: "LGPD e Privacidade",
    category: "LGPD e Privacidade",
    categories: ["LGPD e Privacidade"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "12h",
    durationHours: 12,
    level: "Intermediário",
    price: 1090,
    shortDescription: "Função, responsabilidades e rotina operacional do encarregado de dados.",
    fullDescription: "Formação prática para DPOs e equipes de privacidade com foco em atribuições e interface institucional.",
    targetAudience: ["DPOs", "Jurídico", "Privacidade"],
    objectives: ["Clarificar atribuições", "Estruturar a rotina do DPO"],
    benefits: ["Matriz de responsabilidades", "Boas práticas"],
    modules: [],
    instructorId: "instructor-marcos",
    image: "/images/courses/comunicacao-atendimento.jpg",
    rating: 4.8,
    studentsCount: 101,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-dpo-out",
  },
  {
    id: "course-governanca-riscos",
    slug: "governanca-e-gestao-de-riscos-no-setor-publico",
    title: "Governança e gestão de riscos no setor público",
    pathId: "path-gestao-publica",
    pathName: "Gestão Pública",
    category: "Gestão Pública",
    categories: ["Gestão Pública"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "16h",
    durationHours: 16,
    level: "Avançado",
    price: 1290,
    shortDescription: "Governança, riscos e tomada de decisão com base em práticas aplicáveis ao setor público.",
    fullDescription: "Curso orientado à implementação de governança e gestão de riscos na rotina pública.",
    targetAudience: ["Gestão", "Governança", "Controle interno"],
    objectives: ["Estruturar matriz de riscos", "Fortalecer governança"],
    benefits: ["Ferramentas práticas", "Casos aplicados"],
    modules: [],
    instructorId: "instructor-roberto",
    image: "/images/courses/pessoas-lideranca.jpg",
    rating: 4.9,
    studentsCount: 118,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-riscos-nov",
  },
  {
    id: "course-prevencao-fraude",
    slug: "prevencao-a-fraude-e-corrupcao-em-compras",
    title: "Prevenção à fraude e corrupção em compras",
    pathId: "path-compliance",
    pathName: "Compliance",
    category: "Compliance",
    categories: ["Compliance"],
    modality: "Presencial",
    modalities: ["Presencial"],
    durationLabel: "16h",
    durationHours: 16,
    level: "Intermediário",
    price: 1490,
    shortDescription: "Práticas de prevenção à fraude e corrupção com foco em compras públicas.",
    fullDescription: "Capacitação para áreas de compras e integridade sobre prevenção, detecção e resposta a fraudes.",
    targetAudience: ["Compras", "Compliance", "Auditoria"],
    objectives: ["Mapear riscos", "Fortalecer controles de compras"],
    benefits: ["Matriz de controles", "Casos reais"],
    modules: [],
    instructorId: "instructor-fernanda",
    image: "/images/courses/comunicacao-atendimento.jpg",
    rating: 4.8,
    studentsCount: 104,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-fraude-nov",
  },
  {
    id: "course-pregao-eletronico",
    slug: "pregao-eletronico-conducao-e-julgamento",
    title: "Pregão eletrônico: condução e julgamento",
    pathId: "path-licitacoes",
    pathName: "Licitações e Contratos",
    category: "Licitações e Contratos",
    categories: ["Licitações e Contratos"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "12h",
    durationHours: 12,
    level: "Intermediário",
    price: 990,
    shortDescription: "Condução, julgamento e boas práticas em pregão eletrônico.",
    fullDescription: "Curso prático para condução e julgamento de pregão eletrônico com foco em segurança decisória.",
    targetAudience: ["Pregoeiros", "Compras públicas", "Apoio técnico"],
    objectives: ["Conduzir sessões com segurança", "Padronizar julgamento"],
    benefits: ["Roteiros e modelos", "Casos operacionais"],
    modules: [],
    instructorId: "instructor-helena",
    image: "/images/courses/departamento-pessoal-esocial.jpg",
    rating: 4.7,
    studentsCount: 95,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-pregao-dez",
  },
];

export const mockClasses: TrainingClass[] = [
  {
    id: "class-licitacoes-ago",
    courseId: "course-nova-lei-licitacoes",
    startDate: "2026-08-12T09:00:00.000Z",
    endDate: "2026-08-13T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-helena",
    totalSeats: 20,
    manualFilledSeats: 16,
    filledSeats: 16,
    availableSeats: 4,
    status: "Poucas vagas",
    price: 1290,
    notes: "Turma regular.",
  },
  {
    id: "class-lgpd-ago",
    courseId: "course-lgpd-setor-publico",
    startDate: "2026-08-26T09:00:00.000Z",
    endDate: "2026-08-28T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Presencial",
    location: "Brasília, DF",
    instructorId: "instructor-marcos",
    totalSeats: 30,
    manualFilledSeats: 10,
    filledSeats: 10,
    availableSeats: 20,
    status: "Inscrições abertas",
    price: 1690,
    notes: "Turma presencial confirmada.",
  },
  {
    id: "class-contratos-set",
    courseId: "course-gestao-contratos",
    startDate: "2026-09-09T09:00:00.000Z",
    endDate: "2026-09-09T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-helena",
    totalSeats: 25,
    manualFilledSeats: 0,
    filledSeats: 0,
    availableSeats: 25,
    status: "Em breve",
    price: 990,
    notes: "Turma nova.",
  },
  {
    id: "class-compliance-set",
    courseId: "course-programa-integridade",
    startDate: "2026-09-23T09:00:00.000Z",
    endDate: "2026-09-24T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-fernanda",
    totalSeats: 24,
    manualFilledSeats: 8,
    filledSeats: 8,
    availableSeats: 16,
    status: "Inscrições abertas",
    price: 1190,
    notes: "Turma confirmada.",
  },
  {
    id: "class-orcamento-out",
    courseId: "course-planejamento-orcamentario",
    startDate: "2026-10-07T09:00:00.000Z",
    endDate: "2026-10-09T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Presencial",
    location: "São Paulo, SP",
    instructorId: "instructor-roberto",
    totalSeats: 24,
    manualFilledSeats: 19,
    filledSeats: 19,
    availableSeats: 5,
    status: "Poucas vagas",
    price: 1890,
    notes: "Turma com poucas vagas.",
  },
  {
    id: "class-dpo-out",
    courseId: "course-dpo",
    startDate: "2026-10-21T09:00:00.000Z",
    endDate: "2026-10-22T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-marcos",
    totalSeats: 24,
    manualFilledSeats: 9,
    filledSeats: 9,
    availableSeats: 15,
    status: "Inscrições abertas",
    price: 1090,
    notes: "Turma confirmada.",
  },
  {
    id: "class-riscos-nov",
    courseId: "course-governanca-riscos",
    startDate: "2026-11-04T09:00:00.000Z",
    endDate: "2026-11-05T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-roberto",
    totalSeats: 22,
    manualFilledSeats: 0,
    filledSeats: 0,
    availableSeats: 22,
    status: "Em breve",
    price: 1290,
    notes: "Turma nova.",
  },
  {
    id: "class-fraude-nov",
    courseId: "course-prevencao-fraude",
    startDate: "2026-11-18T09:00:00.000Z",
    endDate: "2026-11-19T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Presencial",
    location: "Brasília, DF",
    instructorId: "instructor-fernanda",
    totalSeats: 22,
    manualFilledSeats: 8,
    filledSeats: 8,
    availableSeats: 14,
    status: "Inscrições abertas",
    price: 1490,
    notes: "Turma presencial confirmada.",
  },
  {
    id: "class-pregao-dez",
    courseId: "course-pregao-eletronico",
    startDate: "2026-12-02T09:00:00.000Z",
    endDate: "2026-12-02T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Online ao vivo",
    instructorId: "instructor-helena",
    totalSeats: 20,
    manualFilledSeats: 16,
    filledSeats: 16,
    availableSeats: 4,
    status: "Poucas vagas",
    price: 990,
    notes: "Turma final do calendário.",
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: "instructor-helena",
    name: "Dra. Helena Prado",
    email: "helena.prado@synkra.com.br",
    phone: "(61) 99999-2222",
    specialty: "Licitações e contratos administrativos",
    bio: "Especialista em licitações, gestão contratual e condução de pregões.",
    education: "Doutora em Direito Administrativo",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Helena",
    courseIds: ["course-nova-lei-licitacoes", "course-gestao-contratos", "course-pregao-eletronico"],
    rating: 4.9,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Helena",
    status: "Ativo",
  },
  {
    id: "instructor-marcos",
    name: "Marcos Vinicius",
    email: "marcos.vinicius@synkra.com.br",
    phone: "(61) 99999-3333",
    specialty: "LGPD e privacidade",
    bio: "Consultor em adequação à LGPD, governança de dados e proteção da informação.",
    education: "Especialização em Proteção de Dados",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcos",
    courseIds: ["course-lgpd-setor-publico", "course-dpo"],
    rating: 4.7,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcos",
    status: "Ativo",
  },
  {
    id: "instructor-fernanda",
    name: "Fernanda Lopes",
    email: "fernanda.lopes@synkra.com.br",
    phone: "(61) 99999-4444",
    specialty: "Compliance e integridade",
    bio: "Especialista em integridade pública, prevenção à fraude e cultura de compliance.",
    education: "MBA em Compliance",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda",
    courseIds: ["course-programa-integridade", "course-prevencao-fraude"],
    rating: 4.8,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda",
    status: "Ativo",
  },
  {
    id: "instructor-roberto",
    name: "Roberto Aguiar",
    email: "roberto.aguiar@synkra.com.br",
    phone: "(61) 99999-5555",
    specialty: "Gestão pública, orçamento e riscos",
    bio: "Consultor em governança pública, planejamento orçamentário e gestão de riscos.",
    education: "Mestrado em Administração Pública",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto",
    courseIds: ["course-planejamento-orcamentario", "course-governanca-riscos"],
    rating: 4.9,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto",
    status: "Ativo",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "post-licitacoes-erros-2026",
    title: "Nova Lei de Licitações: os 7 erros que ainda travam pregões em 2026",
    slug: "nova-lei-licitacoes-7-erros-pregoes-2026",
    summary: "Depois da transição definitiva para a Lei 14.133/21, os mesmos deslizes seguem aparecendo nos editais e nas comissões.",
    content:
      "A adoção integral da Lei 14.133/21 não eliminou os erros recorrentes de planejamento e condução.\n\nOs problemas mais frequentes continuam aparecendo antes mesmo da disputa: estudo técnico superficial, critérios mal justificados e termos de referência frágeis.\n\nQuando a equipe revisa essas etapas com antecedência, o pregão deixa de ser um campo de correção emergencial e volta a ser um processo previsível.",
    category: "Licitações",
    tags: ["Licitações", "Lei 14.133", "Pregão"],
    author: "Ana Ribeiro",
    date: "2026-06-28",
    readingTime: "8 min",
    status: "Publicado",
    image: "/images/courses/licitacoes-contratos.jpg",
    relatedCourseId: "course-nova-lei-licitacoes",
  },
  {
    id: "post-pesquisa-precos-tcu",
    title: "Pesquisa de preços: como montar uma que resiste ao TCU",
    slug: "pesquisa-de-precos-como-montar-uma-que-resiste-ao-tcu",
    summary: "O passo a passo para documentar a estimativa de valor sem cair nas inconsistências que mais geram apontamento.",
    content:
      "A pesquisa de preços continua sendo uma das etapas mais sensíveis da fase preparatória.\n\nO problema raramente está só na fonte escolhida, mas na coerência entre objeto, critério e justificativa do valor estimado.\n\nQuando a equipe organiza esses registros com rastreabilidade, a análise de controle fica muito mais defensável.",
    category: "Licitações",
    tags: ["Licitações", "Pesquisa de preços", "TCU"],
    author: "Ana Ribeiro",
    date: "2026-06-24",
    readingTime: "6 min",
    status: "Publicado",
    image: "/images/courses/licitacoes-contratos.jpg",
    relatedCourseId: "course-nova-lei-licitacoes",
  },
  {
    id: "post-alertas-esocial",
    title: "3 alertas para revisar antes de enviar eventos do eSocial",
    slug: "3-alertas-para-revisar-antes-de-enviar-eventos-do-esocial",
    summary: "Um roteiro enxuto para reduzir rejeições, inconsistências cadastrais e retrabalho no fechamento mensal.",
    content:
      "Antes de transmitir eventos periódicos, a conferência de cadastros, rubricas e vínculos evita boa parte dos bloqueios operacionais.\n\nO segundo alerta é garantir coerência entre folha, jornadas e afastamentos, porque a divergência entre bases costuma aparecer só na última hora.\n\nPor fim, vale revisar a trilha de validação e responsabilidade entre RH, DP e fornecedor do sistema para reduzir o vai e vem do fechamento.",
    category: "Departamento Pessoal",
    tags: ["eSocial", "Departamento Pessoal", "Rotina"],
    author: "Carlos Menezes",
    date: "2026-06-24",
    readingTime: "6 min",
    status: "Publicado",
    image: "/images/courses/departamento-pessoal-esocial.jpg",
    relatedCourseId: "course-nova-lei-licitacoes",
  },
  {
    id: "post-ripd-opcional",
    title: "Relatório de impacto (RIPD): quando ele deixa de ser opcional",
    slug: "ripd-quando-deixa-de-ser-opcional",
    summary: "Nem todo tratamento exige um RIPD, mas ignorá-lo nos casos certos é o erro que mais expõe o órgão.",
    content:
      "A dúvida sobre a obrigatoriedade do RIPD normalmente nasce da ausência de critérios claros de risco e sensibilidade.\n\nEm órgãos públicos, o documento ganha relevância quando há tratamento em larga escala, uso de dados sensíveis ou impacto direto em direitos dos titulares.\n\nA boa prática é transformar o RIPD em instrumento de decisão, e não em anexo burocrático produzido só para auditoria.",
    category: "LGPD",
    tags: ["LGPD", "RIPD", "Privacidade"],
    author: "Carlos Menezes",
    date: "2026-06-20",
    readingTime: "7 min",
    status: "Publicado",
    image: "/images/courses/lgpd-setor-publico.jpg",
    relatedCourseId: "course-lgpd-setor-publico",
  },
  {
    id: "post-canal-denuncias",
    title: "Canal de denúncias que as pessoas realmente usam",
    slug: "canal-denuncias-que-as-pessoas-realmente-usam",
    summary: "Estrutura, sigilo e resposta: os três pilares que separam um canal eficaz de um canal decorativo.",
    content:
      "Canal de denúncias sem confiança não vira fonte de prevenção, só requisito de fachada.\n\nO desenho precisa combinar linguagem clara, fluxo protegido e resposta visível para quem reporta ou para a organização que acompanha os indicadores.\n\nQuando a apuração demora ou some, o canal perde adesão e a cultura de integridade fica restrita ao discurso.",
    category: "Compliance",
    tags: ["Compliance", "Integridade", "Canal de denúncias"],
    author: "Julia Santos",
    date: "2026-06-17",
    readingTime: "5 min",
    status: "Publicado",
    image: "/images/courses/compliance-integridade.jpg",
    relatedCourseId: "course-programa-integridade",
  },
  {
    id: "post-planejamento-ppa-loa",
    title: "Planejamento orçamentário: do PPA à execução sem surpresas",
    slug: "planejamento-orcamentario-do-ppa-a-execucao-sem-surpresas",
    summary: "Como amarrar planejamento e execução para que o orçamento aprovado vire entrega real ao longo do ano.",
    content:
      "A maior parte dos ruídos de execução nasce quando planejamento e operação trabalham com referências diferentes.\n\nPPA, LDO e LOA precisam ser traduzidos em uma cadência de monitoramento que ajude a priorizar, corrigir e registrar riscos.\n\nSem isso, a execução vira resposta tardia ao desvio, não uma gestão contínua do resultado.",
    category: "Gestão Pública",
    tags: ["Gestão Pública", "Orçamento", "Execução"],
    author: "Roberto Lima",
    date: "2026-06-13",
    readingTime: "9 min",
    status: "Publicado",
    image: "/images/courses/planejamento-orcamentario.jpg",
    relatedCourseId: "course-planejamento-orcamentario",
  },
  {
    id: "post-fiscalizacao-contratos",
    title: "Fiscalização de contratos: o que registrar (e o que não esquecer)",
    slug: "fiscalizacao-de-contratos-o-que-registrar",
    summary: "Um roteiro objetivo para fiscal acompanhar a execução sem virar refém de planilhas soltas.",
    content:
      "Fiscalização eficiente depende menos de volume de documentos e mais de critério para registrar evidências certas.\n\nO fiscal precisa distinguir o que é rotina operacional, desvio contratual e risco que exige escalonamento imediato.\n\nA padronização desses registros reduz conflito com fornecedor e aumenta segurança para decisões posteriores.",
    category: "Licitações",
    tags: ["Licitações", "Contratos", "Fiscalização"],
    author: "Ana Ribeiro",
    date: "2026-06-10",
    readingTime: "6 min",
    status: "Publicado",
    image: "/images/courses/gestao-fiscalizacao-contratos.jpg",
    relatedCourseId: "course-gestao-contratos",
  },
  {
    id: "post-dpo-pratica-publico",
    title: "Encarregado de dados no setor público: função na prática",
    slug: "encarregado-de-dados-no-setor-publico-funcao-na-pratica",
    summary: "Entre a teoria da lei e a rotina do órgão: o que o DPO faz de verdade na primeira semana.",
    content:
      "O encarregado de dados precisa operar como ponto de coordenação, não como balcão de dúvidas isolado.\n\nIsso significa organizar resposta a titulares, orientar áreas e criar uma agenda mínima de governança com jurídico, TI e gestão.\n\nSem clareza de papel, a função vira um endereço formal sem capacidade real de resposta.",
    category: "LGPD",
    tags: ["LGPD", "DPO", "Setor Público"],
    author: "Carlos Menezes",
    date: "2026-06-05",
    readingTime: "8 min",
    status: "Publicado",
    image: "/images/courses/lgpd-setor-publico.jpg",
    relatedCourseId: "course-dpo",
  },
  {
    id: "post-due-diligence",
    title: "Due diligence de fornecedores sem burocratizar a compra",
    slug: "due-diligence-de-fornecedores-sem-burocratizar-a-compra",
    summary: "Proporcionalidade é a palavra: como avaliar risco de terceiros sem travar o setor de compras.",
    content:
      "A diligência de terceiros só funciona quando o critério acompanha o risco e a criticidade do contrato.\n\nChecklists extensos para todos os casos criam lentidão e pouca inteligência de análise.\n\nO desenho mais eficiente combina perguntas base, gatilhos de aprofundamento e evidência objetiva para decisão.",
    category: "Compliance",
    tags: ["Compliance", "Fornecedores", "Due diligence"],
    author: "Julia Santos",
    date: "2026-06-02",
    readingTime: "5 min",
    status: "Publicado",
    image: "/images/courses/compliance-integridade.jpg",
    relatedCourseId: "course-prevencao-fraude",
  },
  {
    id: "post-matriz-riscos",
    title: "Gestão de riscos: transformando matriz em decisão",
    slug: "gestao-de-riscos-transformando-matriz-em-decisao",
    summary: "A matriz de risco só vale se muda uma decisão. Veja como sair do documento de gaveta para a ação.",
    content:
      "Mapear risco não é o fim do processo, é só o início da priorização gerencial.\n\nA matriz passa a ter valor quando orienta responsáveis, revisão de controles e critérios de acompanhamento.\n\nSem esse vínculo com decisão, ela vira um artefato elegante e pouco útil para a operação.",
    category: "Gestão Pública",
    tags: ["Gestão Pública", "Riscos", "Governança"],
    author: "Roberto Lima",
    date: "2026-05-29",
    readingTime: "7 min",
    status: "Publicado",
    image: "/images/courses/governanca-riscos.jpg",
    relatedCourseId: "course-governanca-riscos",
  },
  {
    id: "post-pregao-eletronico-atencao",
    title: "Pregão eletrônico: os pontos de atenção no julgamento",
    slug: "pregao-eletronico-pontos-de-atencao-no-julgamento",
    summary: "Diligência, negociação e habilitação: onde a condução do pregão costuma escorregar.",
    content:
      "O julgamento do pregão concentra boa parte das decisões que depois viram questionamento formal.\n\nA equipe precisa registrar negociação, diligência e interpretação de requisitos com consistência entre os casos.\n\nQuando isso não acontece, o procedimento perde previsibilidade e aumenta a chance de disputa desnecessária.",
    category: "Licitações",
    tags: ["Licitações", "Pregão", "Julgamento"],
    author: "Ana Ribeiro",
    date: "2026-05-25",
    readingTime: "6 min",
    status: "Publicado",
    image: "/images/courses/licitacoes-contratos.jpg",
    relatedCourseId: "course-pregao-eletronico",
  }
];

export const mockCatalog = {
  courses: mockCourses,
  classes: mockClasses,
  instructors: mockInstructors,
  trainingPaths: mockTrainingPaths,
};
