/**
 * Mock data for public pages when Supabase is unavailable or returns empty.
 * Used as fallback during tests or development.
 */

import type { BlogPost, Course, Instructor, TrainingClass, TrainingPath } from "@/types";

export const mockTrainingPaths: TrainingPath[] = [
  {
    id: "path-dp",
    code: "DP",
    name: "Departamento Pessoal",
    shortName: "DP",
    slug: "departamento-pessoal",
    description: "Rotina trabalhista e folha para equipes de RH.",
    icon: "Calculator",
    courseCount: 3,
  },
  {
    id: "path-esocial",
    code: "ES",
    name: "eSocial",
    shortName: "eSocial",
    slug: "esocial",
    description: "Obrigações e rotinas do eSocial.",
    icon: "BarChart3",
    courseCount: 2,
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-esocial-pratico",
    slug: "esocial-pratico",
    title: "eSocial Prático",
    pathId: "path-esocial",
    pathName: "eSocial",
    category: "eSocial",
    categories: ["eSocial", "Departamento Pessoal"],
    modality: "Ao vivo online",
    modalities: ["Ao vivo online"],
    durationLabel: "16h",
    durationHours: 16,
    level: "Intermediário",
    price: 1200,
    shortDescription: "Operação prática de eventos do eSocial.",
    fullDescription: "Curso aplicado para fechamento, conferência e rotinas do eSocial.",
    targetAudience: ["Analistas de RH", "Departamento pessoal"],
    objectives: ["Validar eventos periódicos", "Reduzir inconsistências"],
    benefits: ["Checklists operacionais", "Casos práticos"],
    modules: [
      {
        title: "Eventos periódicos",
        description: "Conferência de remuneração e fechamento.",
        topics: ["S-1200", "S-1210"],
        duration: "8h",
      },
    ],
    instructorId: "instructor-ana",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop",
    rating: 4.8,
    studentsCount: 127,
    status: "Ativo",
    featured: true,
    featuredCourseIds: [],
    nextClassId: "class-esocial-jul",
  },
  {
    id: "course-folha-pagamento",
    slug: "folha-pagamento-essencial",
    title: "Folha de Pagamento Essencial",
    pathId: "path-dp",
    pathName: "Departamento Pessoal",
    category: "Departamento Pessoal",
    categories: ["Departamento Pessoal", "Folha"],
    modality: "Presencial",
    modalities: ["Presencial", "Ao vivo online"],
    durationLabel: "24h",
    durationHours: 24,
    level: "Básico",
    price: 1500,
    shortDescription: "Fundamentos de folha de pagamento e legislação trabalhista.",
    fullDescription: "Capacitação completa para profissionais iniciantes em rotinas de folha.",
    targetAudience: ["Profissionais de RH", "Analistas de Folha"],
    objectives: ["Dominar cálculos de folha", "Aplicar legislação"],
    benefits: ["Certificado", "Materiais didáticos"],
    modules: [
      {
        title: "Fundamentos legais",
        description: "CLT, MP, encargos.",
        topics: ["CLT", "Contribuições"],
        duration: "8h",
      },
    ],
    instructorId: "instructor-carlos",
    image: "https://images.unsplash.com/photo-1554224311-beee415c15c9?w=500&h=300&fit=crop",
    rating: 4.6,
    studentsCount: 89,
    status: "Ativo",
    featured: false,
    featuredCourseIds: [],
    nextClassId: "class-folha-ago",
  },
  {
    id: "course-gestao-publica",
    slug: "gestao-publica-moderna",
    title: "Gestão Pública Moderna",
    pathId: "path-dp",
    pathName: "Departamento Pessoal",
    category: "Gestão Pública",
    categories: ["Gestão Pública", "Administração"],
    modality: "Híbrido",
    modalities: ["Híbrido"],
    durationLabel: "20h",
    durationHours: 20,
    level: "Avançado",
    price: 2000,
    shortDescription: "Práticas modernas de gestão para órgãos públicos.",
    fullDescription: "Estratégias e ferramentas para modernizar a gestão pública.",
    targetAudience: ["Gestores públicos", "Coordenadores"],
    objectives: ["Modernizar processos", "Aumentar eficiência"],
    benefits: ["Networking", "Casos reais"],
    modules: [],
    instructorId: "instructor-mariana",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop",
    rating: 4.9,
    studentsCount: 156,
    status: "Ativo",
    featured: true,
    featuredCourseIds: [],
    nextClassId: "class-gestao-set",
  },
];

export const mockClasses: TrainingClass[] = [
  {
    id: "class-esocial-jul",
    courseId: "course-esocial-pratico",
    startDate: "2026-07-10T09:00:00.000Z",
    endDate: "2026-07-11T18:00:00.000Z",
    time: "09:00 - 18:00",
    modality: "Ao vivo online",
    location: "Sala virtual",
    instructorId: "instructor-ana",
    totalSeats: 20,
    manualFilledSeats: 1,
    filledSeats: 6,
    availableSeats: 14,
    status: "Inscrições abertas",
    price: 1200,
    notes: "Turma regular.",
  },
  {
    id: "class-folha-ago",
    courseId: "course-folha-pagamento",
    startDate: "2026-08-01T14:00:00.000Z",
    endDate: "2026-08-05T18:00:00.000Z",
    time: "14:00 - 18:00",
    modality: "Presencial",
    location: "São Paulo, SP",
    instructorId: "instructor-carlos",
    totalSeats: 30,
    manualFilledSeats: 18,
    filledSeats: 18,
    availableSeats: 12,
    status: "Poucas vagas",
    price: 1500,
    notes: "Última turma do semestre.",
  },
  {
    id: "class-gestao-set",
    courseId: "course-gestao-publica",
    startDate: "2026-09-15T09:00:00.000Z",
    endDate: "2026-09-19T17:00:00.000Z",
    time: "09:00 - 17:00",
    modality: "Híbrido",
    location: "Brasília, DF (+ online)",
    instructorId: "instructor-mariana",
    totalSeats: 25,
    manualFilledSeats: 0,
    filledSeats: 0,
    availableSeats: 25,
    status: "Em breve",
    price: 2000,
    notes: "Turma especial com gestores estaduais.",
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: "instructor-ana",
    name: "Ana Lima",
    email: "ana.lima@synkra.com.br",
    phone: "(61) 99999-2222",
    specialty: "eSocial e folha",
    bio: "Especialista em rotinas trabalhistas com 15 anos de experiência.",
    education: "MBA em Gestão de Pessoas",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    courseIds: ["course-esocial-pratico"],
    rating: 4.9,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    status: "Ativo",
  },
  {
    id: "instructor-carlos",
    name: "Carlos Mendes",
    email: "carlos.mendes@synkra.com.br",
    phone: "(61) 99999-3333",
    specialty: "Folha de pagamento",
    bio: "Consultor especializado em cálculos de folha e legislação trabalhista.",
    education: "Especialização em Direito do Trabalho",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    courseIds: ["course-folha-pagamento"],
    rating: 4.7,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    status: "Ativo",
  },
  {
    id: "instructor-mariana",
    name: "Mariana Silva",
    email: "mariana.silva@synkra.com.br",
    phone: "(61) 99999-4444",
    specialty: "Gestão pública",
    bio: "Gestora experiente em transformação digital de órgãos públicos.",
    education: "Doutorado em Administração Pública",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana",
    courseIds: ["course-gestao-publica"],
    rating: 4.8,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana",
    status: "Ativo",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "post-esocial-checklist",
    title: "Checklist de eSocial: Pontos essenciais para fechamento",
    slug: "checklist-esocial",
    summary: "Guia prático com pontos essenciais para fechamento do eSocial.",
    content: "Conteúdo completo sobre eSocial...",
    category: "eSocial",
    tags: ["eSocial", "RH", "Compliance"],
    author: "Equipe Synkra",
    date: "2026-06-01",
    readingTime: "5 min",
    status: "Publicado",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop",
    relatedCourseId: "course-esocial-pratico",
  },
  {
    id: "post-folha-dicas",
    title: "5 Dicas para organizar a folha de pagamento",
    slug: "5-dicas-folha-pagamento",
    summary: "Estratégias práticas para manter a folha organizada e atualizada.",
    content: "Dicas e truques para rotinas de folha...",
    category: "Departamento Pessoal",
    tags: ["Folha", "Organização", "Produtividade"],
    author: "Carlos Mendes",
    date: "2026-05-28",
    readingTime: "8 min",
    status: "Publicado",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=300&fit=crop",
    relatedCourseId: "course-folha-pagamento",
  },
  {
    id: "post-gestao-moderna",
    title: "Gestão Ágil no Setor Público: é possível?",
    slug: "gestao-agil-setor-publico",
    summary: "Análise sobre implementação de metodologias ágeis em órgãos públicos.",
    content: "Estudo de caso sobre transformação digital...",
    category: "Gestão Pública",
    tags: ["Gestão", "Ágil", "Setor Público"],
    author: "Mariana Silva",
    date: "2026-05-20",
    readingTime: "10 min",
    status: "Publicado",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop",
    relatedCourseId: "course-gestao-publica",
  },
];

export const mockCatalog = {
  courses: mockCourses,
  classes: mockClasses,
  instructors: mockInstructors,
  trainingPaths: mockTrainingPaths,
};
